In [ ]:
pip install pandas

Requirement already satisfied: pandas in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\smanoharan\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\smanoharan\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,roc_auc_score,auc,roc_curve,mean_absolute_error,mean_squared_error,r2_score
from sklearn.tree import DecisionTreeClassifier

In [5]:
cars_data = pd.read_csv('Cars.csv')
cars_data

     HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [6]:
cars_data.isna().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [8]:
cars_data.dtypes  
cars_data.describe()

               HP        MPG         VOL          SP         WT
count   81.000000  81.000000   81.000000   81.000000  81.000000
mean   117.469136  34.422076   98.765432  121.540272  32.412577
std     57.113502   9.131445   22.301497   14.181432   7.492813
min     49.000000  12.101263   50.000000   99.564907  15.712859
25%     84.000000  27.856252   89.000000  113.829145  29.591768
50%    100.000000  35.152727  101.000000  118.208698  32.734518
75%    140.000000  39.531633  113.000000  126.404312  37.392524
max    322.000000  53.700681  160.000000  169.598513  52.997752

In [45]:
X = cars_data[[ "HP","VOL"]]
X

     HP  VOL
0    49   89
1    55   92
2    55   92
3    70   92
4    53   92
..  ...  ...
76  322   50
77  238  115
78  263   50
79  295  119
80  236  107

[81 rows x 2 columns]

In [14]:
y = cars_data["MPG"]
y

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
        ...
76    36.900000
77    19.197888
78    34.000000
79    19.833733
80    12.101263
Name: MPG, Length: 81, dtype: float64

In [41]:
linear_model = LinearRegression()

In [46]:
linear_model.fit(X,y)

LinearRegression()

In [49]:
r2_score(y,y_pred)

0.7506606277376424

In [47]:
y_pred = linear_model.predict(X)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

In [52]:
X_train

     HP  VOL
66  165  114
30   84  114
47   98  103
72  162  132
5    70   89
..  ...  ...
45  100   99
32  102   97
52  115  124
42  102   92
56   96   92

[64 rows x 2 columns]

In [57]:
y_pred_train = linear_model.predict(X_train)

In [53]:
X_test

     HP  VOL
12   92   99
51  115  101
73  140  160
14   66   89
71  162  135
37  102   86
78  263   50
1    55   92
38  102   86
31   84  101
20   92   99
50  115  101
2    55   92
10   73   89
33  102  113
40   95  113
39  130   92

In [58]:
y_pred_test = linear_model.predict(X_test)

In [54]:
y_test

12    39.354094
51    29.629936
73    19.086341
14    45.734893
71    23.203569
37    34.070668
78    34.000000
1     50.013401
38    34.070668
31    39.431235
20    38.411003
50    29.629936
2     50.013401
10    44.652834
33    36.285456
40    35.152727
39    31.014131
Name: MPG, dtype: float64

In [55]:
y_train

66    23.103172
30    39.431235
47    35.052330
72    23.203569
5     45.696322
        ...
45    34.561499
32    36.285456
52    29.629936
42    34.070668
56    31.113584
Name: MPG, Length: 64, dtype: float64

In [48]:
mean_absolute_error(y,y_pred)

3.5677837838327053

In [56]:
mean_squared_error(y,y_pred)

20.534059667089817

In [59]:
mean_absolute_error(y_test, y_pred_test)

3.5624401851072673

In [60]:
mean_absolute_error(y_train, y_pred_train)

3.56920317724415

In [61]:
mean_squared_error(y_train,y_pred_train)

21.48559423805864

In [62]:
mean_squared_error(y_test, y_pred_test)

16.951811870501327