In [6]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import AdaBoostClassifier

In [10]:
environment= pd.read_csv("environmental_data.csv")
environment

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [11]:
environment.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C            str
Month             str
Day             int64
Year            int64
Temp            int64
Weather           str
dtype: object

In [12]:
environment.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [13]:
environment.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [14]:
environment.drop(columns=["Unnamed: 0","Temp C"], inplace=True)

In [18]:
## we have removed two colums from the dataset. The first one is an index column and the second one is a temperature column which has a lot of missing values. We will see how to handle missing values in the next section.

In [15]:
environment

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [16]:
del environment["Ozone"]

In [17]:
environment[environment["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [18]:
environment.groupby("Weather")["Solar.R"].mean()

Weather
C     192.391304
PS    174.347826
S     193.333333
Name: Solar.R, dtype: float64

In [19]:
environment["Solar.R"] = environment["Solar.R"].transform(lambda x: x.fillna(x.mean()).round(2))

In [20]:
environment.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [21]:
environment.dropna(inplace=True)

In [22]:
environment.dtypes

Solar.R    float64
Wind       float64
Month          str
Day          int64
Year         int64
Temp         int64
Weather        str
dtype: object

In [23]:
environment["Month"].unique()

<StringArray>
['5', 'May', '6', '7', '8', '9']
Length: 6, dtype: str

In [24]:
environment["Month"] = environment["Month"].replace(to_replace = "May", value = '5')

In [25]:
environment["Month"] = environment["Month"].astype("int64")

In [26]:
environment["Weather"].unique()

<StringArray>
['S', 'C', 'PS']
Length: 3, dtype: str

In [27]:
en_copy1 = environment.copy()

In [28]:
en_copy2 = environment.copy()

In [29]:
en_copy1

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      185.4  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [30]:
label_encoder = LabelEncoder()

In [31]:
en_copy1["Weather"] = label_encoder.fit_transform(en_copy1["Weather"])

In [94]:
## after the label encoding, the weather column has been transformed into numerical values. The unique values in the weather column have been replaced with integers. 
#The mapping of the original values to the integers can be obtained using the classes_ attribute of the label encoder.
## the weather column the data defined as follows:
# 2: "Sunny"
# 0: "Cloudy"  
# 1: "partly cloudy"

In [32]:
en_copy1

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      185.4  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
onehot_encoder = OneHotEncoder()

In [35]:
en_copy2

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      185.4  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [36]:
en_copy2[["Weather_C","Weather_PS", "Weather_S"]] = onehot_encoder.fit_transform(en_copy2[["Weather"]]).todense().round()

In [37]:
en_copy2

,Solar.R,Wind,Month,Day,Year,Temp,Weather,Weather_C,Weather_PS,Weather_S
0,190.0,7.4,5,1,2010,67,S,0.0,0.0,1.0
1,118.0,8.0,5,2,2010,72,C,1.0,0.0,0.0
2,149.0,12.6,5,3,2010,74,PS,0.0,1.0,0.0
3,313.0,11.5,5,4,2010,62,S,0.0,0.0,1.0
4,185.4,14.3,5,5,2010,56,S,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
153,190.0,7.4,5,1,2010,67,C,1.0,0.0,0.0
154,193.0,6.9,9,26,2010,70,PS,0.0,1.0,0.0
155,145.0,13.2,9,27,2010,77,S,0.0,0.0,1.0
156,191.0,14.3,9,28,2010,75,S,0.0,0.0,1.0
157,131.0,8.0,9,29,2010,76,C,1.0,0.0,0.0

In [38]:
en_copy2.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather           str
Weather_C     float64
Weather_PS    float64
Weather_S     float64
dtype: object

In [39]:
ada_boost = AdaBoostClassifier()

In [40]:
ada_boost.predict()

TypeError: AdaBoostClassifier.predict() missing 1 required positional argument: 'X'